import { useEffect } from 'react';
import { getLang } from '@/lib/i18n';
import { setSeo } from '@/lib/seo';
import LegalPageLayout from '@/components/legal/LegalPageLayout';

export default function Offer() {
  const lang = getLang();
  const isRu = lang === 'ru';

  useEffect(() => {
    setSeo({
      title: isRu ? 'Публичная оферта' : 'Public Offer',
      description: isRu
        ? 'Публичная оферта на оказание услуг сервиса Roboweb — условия использования AI-конструктора сайтов.'
        : 'Public offer for Roboweb services — terms of use for the AI website builder.',
      url: '/oferta',
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  if (!isRu) {
    return (
      <LegalPageLayout title="Public Offer Agreement" updatedAt="July 4, 2026">
        <p>
          This Public Offer Agreement (the "Agreement") is published at roboweb.site (the "Service") and constitutes
          a formal offer by Individual Entrepreneur Arakelov Stanislav Vladislavovich (OGRNIP 324508100357892, TIN 501210007760),
          hereinafter referred to as the "Contractor", to any individual or legal entity (the "User") to use the Service
          on the terms set out below, in accordance with Article 437 of the Civil Code of the Russian Federation.
        </p>
        <h2>1. Subject of the Agreement</h2>
        <p>
          1.1. The Contractor grants the User access to Roboweb — a cloud-based AI service for generating, editing,
          hosting and publishing websites based on the User's text descriptions.
        </p>
        <p>1.2. The Service is provided remotely, via the website roboweb.site, without signing a paper agreement.</p>
        <p>
          1.3. Acceptance of this offer (registering an account and/or paying for a plan) means the User fully and
          unconditionally accepts all terms of this Agreement.
        </p>
        <h2>2. Service Plans and Payment</h2>
        <p>2.1. The Service is provided under several plans:</p>
        <ul>
          <li><strong>Free</strong> — free of charge, 10 one-time AI requests, up to 3 projects.</li>
          <li><strong>Premium</strong> — 999 ₽/month, 40 AI requests per month, custom domain connection.</li>
          <li><strong>Pro (60/80/200/400/800)</strong> — from 2,999 ₽ to 49,999 ₽ per month, with a corresponding
            number of monthly AI requests and increased database/storage/compute limits.</li>
        </ul>
        <p>
          2.2. Payment is accepted via the YooKassa payment system in Russian rubles (RUB), using bank cards,
          SBP, or other methods supported by YooKassa.
        </p>
        <p>2.3. A subscription is billed monthly and renews automatically unless cancelled by the User in the personal account.</p>
        <p>
          2.4. In addition to plan limits, the User may purchase additional "energy" (extra AI requests) as a one-time
          top-up.
        </p>
        <p>2.5. The Contractor may change prices and plan terms; changes apply to future billing periods and do not affect already-paid periods.</p>
        <h2>3. Rights and Obligations of the Parties</h2>
        <p>3.1. The Contractor undertakes to:</p>
        <ul>
          <li>provide access to the Service functionality according to the selected plan;</li>
          <li>ensure the technical operability of the Service to the extent reasonably possible;</li>
          <li>store the User's projects and files for the duration of the active account.</li>
        </ul>
        <p>3.2. The User undertakes to:</p>
        <ul>
          <li>provide accurate registration information;</li>
          <li>not use the Service for illegal purposes, including publishing content that violates the law or third-party rights;</li>
          <li>independently ensure the legality of content generated through the Service before publishing it.</li>
        </ul>
        <h2>4. Content Generated by AI</h2>
        <p>
          4.1. Website content is generated automatically based on the User's prompts using third-party language models
          (including Anthropic Claude and OpenAI GPT-4o/DALL-E). The Contractor does not pre-moderate generated content.
        </p>
        <p>
          4.2. The User is solely responsible for the content of published sites, including compliance with
          intellectual property, advertising and personal data laws.
        </p>
        <h2>5. Liability and Limitations</h2>
        <p>
          5.1. The Service is provided "as is". The Contractor does not guarantee uninterrupted operation and is not
          liable for indirect losses arising from the use or inability to use the Service.
        </p>
        <p>5.2. The Contractor's liability for any claim is limited to the amount paid by the User for the current billing period.</p>
        <h2>6. Refunds and Cancellation</h2>
        <p>
          6.1. The User may request a refund within 7 days of payment if the paid features were not actually used,
          by contacting {`roboweb.site@yandex.ru`}.
        </p>
        <p>6.2. The subscription can be cancelled at any time in the personal account; the paid period remains active until its end date.</p>
        <h2>7. Term and Termination</h2>
        <p>7.1. This Agreement is valid indefinitely from the moment of acceptance until the account is deleted by the User or the Contractor.</p>
        <p>7.2. The Contractor may suspend access in case of violation of these terms or applicable law.</p>
        <h2>8. Final Provisions</h2>
        <p>8.1. This Agreement is governed by the laws of the Russian Federation.</p>
        <p>8.2. All disputes are settled through negotiation; if not resolved, in accordance with the applicable jurisdiction procedure.</p>
        <h2>9. Contractor Details</h2>
        <p>
          Individual Entrepreneur Arakelov Stanislav Vladislavovich<br />
          OGRNIP: 324508100357892<br />
          TIN: 501210007760<br />
          Email: roboweb.site@yandex.ru<br />
          Phone: +7 (933) 177-00-86
        </p>
      </LegalPageLayout>
    );
  }

  return (
    <LegalPageLayout title="Публичная оферта" updatedAt="4 июля 2026 г.">
      <p>
        Настоящий документ является публичной офертой (далее — «Оферта») индивидуального предпринимателя
        Аракелова Станислава Владиславовича (ОГРНИП 324508100357892, ИНН 501210007760), далее — «Исполнитель»,
        адресованной любому физическому или юридическому лицу (далее — «Пользователь») на оказание услуг сервиса
        Roboweb, размещённого по адресу roboweb.site (далее — «Сервис»), в соответствии со ст. 437 Гражданского
        кодекса РФ.
      </p>

      <h2>1. Предмет оферты</h2>
      <p>
        1.1. Исполнитель предоставляет Пользователю доступ к Сервису Roboweb — облачному AI-инструменту для
        генерации, редактирования, размещения (хостинга) и публикации сайтов на основе текстового описания
        Пользователя.
      </p>
      <p>1.2. Услуги оказываются дистанционно через сайт roboweb.site без подписания бумажного договора.</p>
      <p>
        1.3. Акцептом (принятием) настоящей Оферты является регистрация аккаунта на Сервисе и/или оплата
        любого платного тарифа. Акцепт означает полное и безоговорочное согласие Пользователя со всеми условиями
        Оферты.
      </p>

      <h2>2. Тарифы и порядок оплаты</h2>
      <p>2.1. Сервис предоставляется на условиях одного из следующих тарифов:</p>
      <ul>
        <li><strong>Пробный (Free)</strong> — бесплатно, 10 запросов к AI разово, до 3 проектов;</li>
        <li><strong>Премиум</strong> — 999 ₽ в месяц, 40 запросов к AI ежемесячно, подключение собственного домена;</li>
        <li><strong>Профи (Pro 60/80/200/400/800)</strong> — от 2 999 ₽ до 49 999 ₽ в месяц, с соответствующим
          количеством ежемесячных запросов к AI и увеличенными лимитами базы данных, хранилища и вычислений.</li>
      </ul>
      <p>
        2.2. Оплата принимается через платёжную систему ЮKassa в российских рублях банковскими картами,
        через СБП и иными способами, поддерживаемыми ЮKassa.
      </p>
      <p>
        2.3. Платные тарифы оплачиваются по подписке с ежемесячным продлением, если Пользователь не отменил
        подписку в личном кабинете.
      </p>
      <p>
        2.4. Помимо лимита тарифа Пользователь может дополнительно приобрести «энергию» — разовый пакет
        дополнительных запросов к AI.
      </p>
      <p>
        2.5. Исполнитель вправе изменять стоимость и состав тарифов. Изменения применяются к новым расчётным
        периодам и не затрагивают уже оплаченный период.
      </p>

      <h2>3. Права и обязанности сторон</h2>
      <p>3.1. Исполнитель обязуется:</p>
      <ul>
        <li>предоставить доступ к функциональности Сервиса в соответствии с выбранным тарифом;</li>
        <li>обеспечивать техническую работоспособность Сервиса в разумных пределах;</li>
        <li>хранить проекты и файлы Пользователя в течение срока действия аккаунта.</li>
      </ul>
      <p>3.2. Пользователь обязуется:</p>
      <ul>
        <li>предоставлять достоверные данные при регистрации;</li>
        <li>не использовать Сервис в незаконных целях, в том числе для публикации материалов, нарушающих
          законодательство РФ или права третьих лиц;</li>
        <li>самостоятельно нести ответственность за законность контента, сгенерированного с помощью Сервиса,
          перед его публикацией.</li>
      </ul>

      <h2>4. Контент, создаваемый искусственным интеллектом</h2>
      <p>
        4.1. Содержимое сайтов генерируется автоматически на основе запросов Пользователя с использованием
        сторонних языковых моделей (в том числе Anthropic Claude и OpenAI GPT-4o/DALL-E). Исполнитель не
        осуществляет предварительную модерацию сгенерированного контента.
      </p>
      <p>
        4.2. Пользователь несёт единоличную ответственность за содержание публикуемых сайтов, включая
        соблюдение законодательства об интеллектуальной собственности, рекламе и персональных данных.
      </p>

      <h2>5. Ответственность и ограничения</h2>
      <p>
        5.1. Сервис предоставляется «как есть» (as is). Исполнитель не гарантирует бесперебойную работу Сервиса
        и не несёт ответственности за косвенные убытки, возникшие в результате использования или невозможности
        использования Сервиса.
      </p>
      <p>
        5.2. Ответственность Исполнителя по любым претензиям ограничена суммой, уплаченной Пользователем за
        текущий расчётный период.
      </p>

      <h2>6. Возврат средств и отмена подписки</h2>
      <p>
        6.1. Пользователь вправе запросить возврат денежных средств в течение 7 дней с момента оплаты, если
        оплаченные функции фактически не использовались, обратившись по адресу roboweb.site@yandex.ru.
      </p>
      <p>
        6.2. Подписка может быть отменена в любой момент в личном кабинете; оплаченный период действует до
        даты его окончания.
      </p>

      <h2>7. Срок действия и расторжение</h2>
      <p>7.1. Оферта действует бессрочно с момента акцепта до удаления аккаунта Пользователем или Исполнителем.</p>
      <p>7.2. Исполнитель вправе приостановить доступ к Сервису при нарушении условий Оферты или законодательства РФ.</p>

      <h2>8. Заключительные положения</h2>
      <p>8.1. К настоящей Оферте применяется законодательство Российской Федерации.</p>
      <p>8.2. Все споры разрешаются путём переговоров, а при недостижении согласия — в установленном законом порядке.</p>

      <h2>9. Реквизиты Исполнителя</h2>
      <p>
        Индивидуальный предприниматель Аракелов Станислав Владиславович<br />
        ОГРНИП: 324508100357892<br />
        ИНН: 501210007760<br />
        Email: roboweb.site@yandex.ru<br />
        Телефон: 8 (933) 177-00-86
      </p>
    </LegalPageLayout>
  );
}
