import type { Lang } from '@/lib/i18n';
import type { DemoCategory } from './portfolioCategories';

export interface DemoItem {
  tag: string;
  title: string;
  prompt: string;
  img: string;
  color: string;
  category: DemoCategory;
}

const DEMO_ITEMS_RU: DemoItem[] = [
  { category: 'food',     tag: '☕ Кофейня',       title: 'Лендинг для кофейни',        prompt: 'Сделай лендинг для кофейни «Brew & Co» с меню, доставкой и онлайн-заказом',                       img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/b63329a1-4787-4390-9517-4c44d58cbd30.jpg', color: 'from-amber-500 to-orange-500' },
  { category: 'services', tag: '💪 Фитнес',         title: 'Сайт тренера',               prompt: 'Создай сайт для персонального тренера с расписанием, ценами и записью на тренировки',              img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/c60524f9-2093-4c3f-8244-e4d438fea9e6.jpg', color: 'from-slate-700 to-slate-900' },
  { category: 'store',    tag: '👗 Магазин',         title: 'Интернет-магазин одежды',    prompt: 'Сделай интернет-магазин женской одежды с каталогом, фильтрами и корзиной',                         img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/c5508776-143f-474f-a178-41c68eef598e.jpg', color: 'from-rose-400 to-pink-500' },
  { category: 'services', tag: '✂️ Барбершоп',      title: 'Сайт барбершопа с записью',  prompt: 'Создай сайт для барбершопа IronCut с онлайн-записью, ценами и командой мастеров',                 img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/071ec557-3a4c-4dd0-ae9a-45e76a727d04.jpg', color: 'from-zinc-800 to-yellow-600' },
  { category: 'other',    tag: '📷 Фотограф',        title: 'Портфолио фотографа',        prompt: 'Сделай сайт-портфолио для фотографа с галереей, услугами и формой заявки',                         img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/bae125f8-53ae-46c3-a581-22431e0ae59c.jpg', color: 'from-neutral-800 to-neutral-600' },
  { category: 'business', tag: '🏠 Недвижимость',    title: 'Агентство недвижимости',     prompt: 'Создай сайт агентства недвижимости с каталогом объектов, поиском и формой звонка',                 img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/82da60de-0297-440f-9be5-1b5237dd9b82.jpg', color: 'from-blue-600 to-sky-400' },
  { category: 'other',    tag: '🎓 Обучение',        title: 'Платформа онлайн-курсов',    prompt: 'Сделай лендинг для онлайн-курсов по маркетингу с программой, отзывами и оплатой',                  img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/fcf7cba0-ef75-48a1-90cc-67bea38a7a42.jpg', color: 'from-violet-600 to-purple-500' },
  { category: 'business', tag: '⚖️ Юристы',          title: 'Юридическая компания',       prompt: 'Создай сайт юридической фирмы с услугами, командой адвокатов и бесплатной консультацией',          img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/1198e598-58e1-47a8-b077-8e5dbe9ea6f3.jpg', color: 'from-blue-900 to-blue-700' },
  { category: 'services', tag: '🏥 Медицина',        title: 'Медицинская клиника',        prompt: 'Сделай сайт медицинской клиники с услугами, врачами, ценами и записью на приём',                   img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/51100d73-958a-4d7c-af38-a148befee5ff.jpg', color: 'from-emerald-500 to-teal-400' },
  { category: 'food',     tag: '🍕 Доставка еды',    title: 'Сервис доставки еды',        prompt: 'Создай сайт доставки еды с каталогом блюд, корзиной и отслеживанием заказа',                       img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/6f3be26f-b4b9-4216-a21b-f7d6a94b617c.jpg', color: 'from-red-500 to-orange-400' },
  { category: 'services', tag: '💆 Салон красоты',   title: 'Салон красоты и SPA',        prompt: 'Сделай сайт для салона красоты с услугами, мастерами, ценами и онлайн-записью',                    img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/e22098d6-0537-4baa-9062-aa60b82c6d59.jpg', color: 'from-pink-400 to-rose-300' },
  { category: 'business', tag: '🚀 IT-стартап',      title: 'Лендинг SaaS-продукта',      prompt: 'Создай лендинг для IT-стартапа с описанием продукта, тарифами и формой регистрации',               img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/eae8cdf1-1992-4789-8561-5ddc889be53c.jpg', color: 'from-blue-700 to-violet-600' },
  { category: 'other',    tag: '✈️ Туризм',          title: 'Туристическое агентство',    prompt: 'Сделай сайт туристического агентства с турами, направлениями и формой бронирования',              img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/dfcde93a-e603-4c9d-a5ab-a959ff161d99.jpg', color: 'from-cyan-500 to-sky-400' },
  { category: 'other',    tag: '🚗 Автосалон',       title: 'Автосалон и автосервис',     prompt: 'Создай сайт автосалона с каталогом авто, калькулятором кредита и записью на тест-драйв',           img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/5e504f75-6525-48c7-87f4-b209120ae573.jpg', color: 'from-gray-800 to-gray-600' },
  { category: 'other',    tag: '👶 Детский центр',   title: 'Детский развивающий центр',  prompt: 'Сделай сайт детского центра с программами, расписанием, педагогами и записью',                    img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/095d5e48-e227-42ba-9d86-39032ab86121.jpg', color: 'from-yellow-400 to-green-400' },
  { category: 'services', tag: '💍 Свадьба',         title: 'Свадебное агентство',        prompt: 'Создай сайт свадебного агентства с портфолио, пакетами услуг и формой заявки',                     img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/f419a17b-8ed1-45a5-ac7b-e9054e70d419.jpg', color: 'from-amber-200 to-yellow-400' },
  { category: 'business', tag: '📊 Бухгалтерия',    title: 'Бухгалтерские услуги',       prompt: 'Сделай сайт бухгалтерской компании с услугами, ценами и формой консультации',                      img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/d3be1a1d-ab40-4b53-b9c9-55cfaa28b125.jpg', color: 'from-blue-600 to-indigo-500' },
  { category: 'services', tag: '🐾 Ветеринария',    title: 'Ветеринарная клиника',       prompt: 'Создай сайт ветеринарной клиники с услугами, врачами, ценами и записью животного',                 img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/51a9cdb6-da81-4f7f-8bf8-7bf866d7cfd4.jpg', color: 'from-green-500 to-emerald-400' },
  { category: 'services', tag: '🧘 Йога',           title: 'Студия йоги и медитации',    prompt: 'Создай сайт студии йоги с расписанием занятий, инструкторами и онлайн-записью',                    img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/d28560ee-5fe5-4aaf-8897-62e8f7c5d5eb.jpg', color: 'from-green-400 to-teal-600' },
  { category: 'food',     tag: '🍺 Пивоварня',      title: 'Крафтовая пивоварня',        prompt: 'Сделай сайт крафтовой пивоварни с картой напитков, историей бренда и событиями',                   img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/5f1bfd41-dee2-46c0-995b-6416b7e05493.jpg', color: 'from-amber-800 to-yellow-700' },
  { category: 'store',    tag: '📱 Электроника',    title: 'Магазин электроники',        prompt: 'Создай интернет-магазин электроники с каталогом, фильтрами, корзиной и сравнением товаров',         img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/1fd849ce-bc65-498b-8f48-7bcee358cc19.jpg', color: 'from-slate-800 to-blue-600' },
  { category: 'services', tag: '💪 Тренажёрный зал',title: 'Фитнес-клуб',               prompt: 'Сделай сайт фитнес-клуба с абонементами, тренерами, расписанием групповых занятий и акциями',      img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/3572452d-82f0-4abc-8aec-b11cfe23bfd9.jpg', color: 'from-orange-600 to-red-700' },
  { category: 'food',     tag: '🍣 Суши',           title: 'Ресторан суши',              prompt: 'Создай сайт суши-ресторана с онлайн-меню, доставкой и возможностью забронировать столик',           img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/0e7bda52-ffc3-4e96-a45f-3723e6b2017f.jpg', color: 'from-red-700 to-gray-900' },
  { category: 'other',    tag: '🏗️ Строительство',  title: 'Строительная компания',      prompt: 'Создай сайт строительной компании с портфолио объектов, услугами и калькулятором стоимости',       img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/529868f5-42bd-4672-880b-35cfc817c50b.jpg', color: 'from-yellow-500 to-gray-700' },
  { category: 'services', tag: '🌸 Флористика',     title: 'Цветочный магазин',          prompt: 'Сделай сайт цветочного магазина с каталогом букетов, доставкой и конструктором букета',             img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/63778705-6305-438a-aa46-cd5e947749f1.jpg', color: 'from-pink-300 to-rose-500' },
  { category: 'business', tag: '🏡 Дизайн интерьера',title: 'Студия дизайна интерьера', prompt: 'Создай сайт студии дизайна интерьера с портфолио проектов, услугами и формой заявки',              img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/5f7b2af0-4e09-4e35-8c32-7bed84cfd14b.jpg', color: 'from-stone-400 to-amber-200' },
  { category: 'other',    tag: '🧸 Детский сад',    title: 'Частный детский сад',        prompt: 'Сделай сайт частного детского сада с программой, расписанием, педагогами и формой записи',         img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/c8f617a4-68f2-45b4-be34-0ea5896cbabe.jpg', color: 'from-yellow-300 to-orange-400' },
  { category: 'food',     tag: '🥞 Кафе-завтраки',  title: 'Кафе завтраков и бранч',        prompt: 'Сделай сайт уютного кафе завтраков с меню, фото интерьера и онлайн-бронированием столиков',      img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/171439ea-70d7-4fac-9c75-39ea2e184df4.jpg', color: 'from-yellow-300 to-amber-500' },
  { category: 'food',     tag: '🍕 Пиццерия',        title: 'Пиццерия с доставкой',          prompt: 'Создай сайт пиццерии с онлайн-меню, конструктором пиццы и доставкой',                             img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/93642203-cf1c-4b2d-b38d-864fa5cc79f1.jpg', color: 'from-red-600 to-orange-500' },
  { category: 'food',     tag: '🥩 Стейк-хаус',      title: 'Ресторан-гриль',                prompt: 'Сделай сайт стейк-хауса с меню, фото блюд, бронированием столика и описанием атмосферы',          img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/2e51b27a-427a-4069-8a37-c946b1236c4b.jpg', color: 'from-stone-800 to-red-900' },
  { category: 'food',     tag: '🥐 Пекарня',          title: 'Пекарня и кондитерская',        prompt: 'Создай сайт пекарни с каталогом выпечки, акциями дня и возможностью заказа торта',                img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/f3ac426c-8eae-4ebd-8b50-0cafbfc95946.jpg', color: 'from-amber-200 to-orange-300' },
  { category: 'food',     tag: '🥗 Веган-кафе',       title: 'Веган-кафе',                    prompt: 'Сделай сайт веган-кафе с меню, философией бренда, доставкой и картой ингредиентов',               img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/7f0b5522-7cbe-4bad-a7f9-fda740b97a32.jpg', color: 'from-lime-500 to-green-600' },
  { category: 'services', tag: '🧹 Клининг',          title: 'Клининговая компания',          prompt: 'Создай сайт клининговой компании с услугами, ценами, фото до/после и онлайн-заявкой',             img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/9e32de3d-7df2-4816-8c4d-48e24c69d070.jpg', color: 'from-sky-400 to-blue-500' },
  { category: 'services', tag: '🦷 Стоматология',     title: 'Стоматологическая клиника',     prompt: 'Сделай сайт стоматологии с услугами, врачами, ценами и онлайн-записью на приём',                 img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/aef5463f-aba5-4900-b73e-8f25a2ed0797.jpg', color: 'from-cyan-400 to-teal-500' },
  { category: 'services', tag: '🚕 Такси',            title: 'Служба такси и трансфер',       prompt: 'Создай сайт службы такси с калькулятором маршрута, тарифами и онлайн-заказом поездки',            img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/2d7f6ce3-e5de-4005-b01f-8a8dcd106061.jpg', color: 'from-yellow-400 to-gray-800' },
  { category: 'services', tag: '🔧 Ремонт',           title: 'Ремонт квартир и домов',        prompt: 'Сделай сайт ремонтной компании с портфолио работ, услугами, ценами и формой заявки',             img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/4233d966-7d20-4623-9cfd-c17c0afc5146.jpg', color: 'from-orange-500 to-stone-700' },
  { category: 'services', tag: '💆 Массаж',           title: 'Массаж и оздоровительный SPA',  prompt: 'Создай сайт массажного центра с видами массажа, мастерами, прайсом и онлайн-записью',           img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/995ab816-2d94-405e-a307-9e0d16c35279.jpg', color: 'from-stone-300 to-green-700' },
  { category: 'store',    tag: '⚽ Спорттовары',      title: 'Магазин спорттоваров',          prompt: 'Создай интернет-магазин спортивных товаров с каталогом, фильтрами по видам спорта и корзиной',   img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/6f9deb2d-fe19-4c31-ae8d-c61b45cd1024.jpg', color: 'from-orange-500 to-gray-900' },
  { category: 'store',    tag: '💎 Украшения',        title: 'Магазин украшений',             prompt: 'Сделай интернет-магазин украшений ручной работы с каталогом, фильтрами и корзиной',               img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/acd7469d-2d76-4dcb-8821-dddc89e49128.jpg', color: 'from-yellow-600 to-stone-900' },
  { category: 'store',    tag: '🛋️ Мебель',           title: 'Магазин мебели и декора',       prompt: 'Создай интернет-магазин мебели с каталогом по комнатам, 3D-просмотром и оформлением заказа',     img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/201cdcac-25cb-4142-88b9-dbd3b8820757.jpg', color: 'from-amber-100 to-stone-500' },
  { category: 'store',    tag: '🐶 Зоотовары',        title: 'Зоомагазин',                    prompt: 'Сделай интернет-магазин зоотоваров с каталогом по видам животных, доставкой и акциями',          img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/78123911-6bc2-4ebe-b562-bda337933d44.jpg', color: 'from-blue-400 to-yellow-400' },
  { category: 'store',    tag: '💄 Косметика',        title: 'Магазин косметики',             prompt: 'Создай интернет-магазин косметики и ухода с каталогом, отзывами и подбором по типу кожи',        img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/f4063ad2-759f-406a-aba8-238201b45330.jpg', color: 'from-pink-300 to-fuchsia-500' },
  { category: 'business', tag: '🚚 Логистика',        title: 'Логистическая компания',        prompt: 'Создай сайт логистической компании с услугами, калькулятором стоимости доставки и отслеживанием', img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/1eb0c60f-7051-45d9-9f3d-0ac23d103312.jpg', color: 'from-blue-700 to-sky-500' },
  { category: 'business', tag: '👔 HR-агентство',     title: 'Кадровое агентство',            prompt: 'Сделай сайт кадрового агентства с вакансиями, разделами для работодателей и соискателей',        img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/355dbc91-afd6-4070-a83a-971105daf896.jpg', color: 'from-teal-500 to-cyan-700' },
  { category: 'business', tag: '🔒 Охрана',           title: 'Охранная компания',             prompt: 'Создай сайт охранной компании с услугами, объектами, командой и формой заявки на охрану',        img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/51466acd-c488-4536-911d-fb0c18bcf96c.jpg', color: 'from-gray-800 to-red-700' },
  { category: 'business', tag: '🎪 Ивент-агентство',  title: 'Организация мероприятий',       prompt: 'Сделай сайт ивент-агентства с портфолио мероприятий, услугами и формой заявки',                 img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/54bc910d-b0c6-4a0a-a0e7-eaf74a2cd76b.jpg', color: 'from-violet-700 to-amber-500' },
  { category: 'business', tag: '📣 Маркетинг',        title: 'Маркетинговое агентство',       prompt: 'Создай сайт digital-агентства с кейсами, услугами, командой и формой для клиентов',             img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/bf719cbf-5cc6-413c-82ac-15a2953dd59d.jpg', color: 'from-violet-600 to-fuchsia-500' },
  { category: 'other',    tag: '🎸 Школа музыки',     title: 'Музыкальная школа',             prompt: 'Сделай сайт музыкальной школы с курсами, преподавателями, расписанием и записью на пробный урок', img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/dce2e53c-b797-4321-9633-84369b95d2c8.jpg', color: 'from-purple-600 to-pink-500' },
  { category: 'other',    tag: '🔐 Квест-комнаты',    title: 'Квест-комнаты',                 prompt: 'Создай сайт квест-комнат с описанием квестов, сложностью, онлайн-бронированием и ценами',        img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/abdec448-53e7-4f52-9660-2948389d2f8d.jpg', color: 'from-gray-900 to-violet-900' },
  { category: 'other',    tag: '📸 Свадебный фото',   title: 'Свадебный фотограф',            prompt: 'Сделай сайт свадебного фотографа с галереей, пакетами услуг и формой бронирования даты',       img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/87434f77-3485-40db-ad03-2d822588372b.jpg', color: 'from-neutral-700 to-rose-300' },
  { category: 'other',    tag: '🏢 Коворкинг',        title: 'Коворкинг-пространство',        prompt: 'Создай сайт коворкинга с тарифами, фото пространства, удобствами и формой бронирования места',  img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/d31c6e8f-f8b0-4504-8b60-a1b91f14a9d3.jpg', color: 'from-slate-600 to-indigo-500' },
  { category: 'other',    tag: '🌍 Языковая школа',   title: 'Школа иностранных языков',      prompt: 'Сделай сайт языковой школы с курсами, уровнями, преподавателями и тестом для определения уровня', img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/df1929f9-3357-4149-b9f6-b9afefcef8b3.jpg', color: 'from-blue-500 to-yellow-400' },
  { category: 'food',     tag: '🍜 Лапшичная',        title: 'Азиатская лапшичная',            prompt: 'Создай сайт азиатской лапшичной с меню, фото блюд, доставкой и бронированием столика',           img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/e18af4f7-cf34-4688-bac0-ff750d28b298.jpg', color: 'from-red-600 to-amber-500' },
  { category: 'services', tag: '🚗 Автомойка',        title: 'Автомойка и детейлинг',          prompt: 'Сделай сайт автомойки с прайсом услуг, онлайн-записью и фото до/после детейлинга',                img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/f9a0b888-8936-4877-9419-2e2c73a68a22.jpg', color: 'from-blue-500 to-slate-700' },
  { category: 'store',    tag: '📚 Книжный',          title: 'Интернет-магазин книг',          prompt: 'Создай интернет-магазин книг с каталогом по жанрам, рекомендациями и оформлением заказа',         img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/34beb432-f0a7-40b1-ac78-8c65d4a65aeb.jpg', color: 'from-emerald-700 to-lime-600' },
  { category: 'business', tag: '💰 Финансы',          title: 'Финансовый консалтинг',          prompt: 'Сделай сайт финансовой консалтинговой компании с услугами, кейсами и формой заявки на консультацию', img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/53e2183b-5536-43fd-bf81-1909a7134a65.jpg', color: 'from-blue-900 to-amber-500' },
  { category: 'services', tag: '🏃 Реабилитация',     title: 'Центр физиотерапии',             prompt: 'Создай сайт центра реабилитации с услугами, врачами, программами восстановления и записью',      img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/3082f9e0-8de9-4ff1-96b3-03c306575c71.jpg', color: 'from-teal-500 to-cyan-600' },
  { category: 'tech',     tag: '💻 IT-курсы',          title: 'Школа программирования',        prompt: 'Сделай лендинг для школы программирования с курсами, программой обучения и записью на бесплатный урок', img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/13f3efd9-137d-44d9-b7cb-355159a13268.jpg', color: 'from-violet-700 to-indigo-900' },
  { category: 'services', tag: '🎨 Тату-салон',       title: 'Тату-студия',                    prompt: 'Создай сайт тату-студии с портфолио работ, мастерами, ценами и формой записи',                    img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/622a7188-ff1f-4eb1-90f2-75d497ee22e8.jpg', color: 'from-neutral-900 to-red-700' },
  { category: 'business', tag: '🏨 Отель',            title: 'Бутик-отель',                    prompt: 'Сделай сайт бутик-отеля с номерами, ценами, фото интерьера и онлайн-бронированием',                img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/53fb0fd8-8ec5-4999-8ed1-07dd5d05b667.jpg', color: 'from-amber-600 to-emerald-800' },
  { category: 'store',    tag: '🥦 Фермерские продукты', title: 'Магазин органических продуктов', prompt: 'Создай интернет-магазин органических продуктов с каталогом, доставкой и подпиской на еженедельный набор', img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/2fceb611-9776-44eb-9eee-706d5c69f2c2.jpg', color: 'from-lime-600 to-green-800' },
  { category: 'tech',     tag: '📲 Мобильное приложение', title: 'Лендинг мобильного приложения', prompt: 'Сделай лендинг для мобильного приложения с описанием функций, скриншотами и ссылками на скачивание', img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/eae8cdf1-1992-4789-8561-5ddc889be53c.jpg', color: 'from-sky-600 to-indigo-600' },
  { category: 'tech',     tag: '🤖 AI-сервис',        title: 'Лендинг AI-продукта',            prompt: 'Создай лендинг для AI-сервиса с демонстрацией возможностей, тарифами и формой регистрации',        img: 'https://cdn.poehali.dev/projects/a4107a6b-2fca-459b-a931-acd33e9eb6c0/files/fcf7cba0-ef75-48a1-90cc-67bea38a7a42.jpg', color: 'from-fuchsia-600 to-violet-800' },
];

const EN_TAGS = [
  '☕ Coffee','💪 Fitness','👗 Store','✂️ Barbershop','📷 Portfolio',
  '🏠 Real estate','🎓 Education','⚖️ Legal','🏥 Medical','🍕 Food delivery',
  '💆 Beauty salon','🚀 IT startup','✈️ Travel','🚗 Car dealer','👶 Kids center',
  '💍 Wedding','📊 Accounting','🐾 Vet clinic','🧘 Yoga','🍺 Brewery',
  '📱 Electronics','💪 Gym','🍣 Sushi','🏗️ Construction','🌸 Flowers',
  '🏡 Interior design','🧸 Kindergarten','🥞 Brunch cafe','🍕 Pizzeria',
  '🥩 Steakhouse','🥐 Bakery','🥗 Vegan cafe','🧹 Cleaning','🦷 Dentist',
  '🚕 Taxi','🔧 Repair','💆 Massage','⚽ Sports store','💎 Jewelry',
  '🛋️ Furniture','🐶 Pet store','💄 Cosmetics','🚚 Logistics','👔 HR agency',
  '🔒 Security','🎪 Events','📣 Marketing','🎸 Music school','🔐 Quest rooms',
  '📸 Wedding photo','🏢 Coworking','🌍 Language school',
  '🍜 Noodle bar','🚗 Car wash','📚 Bookstore','💰 Finance','🏃 Rehab center',
  '💻 Coding school','🎨 Tattoo studio','🏨 Boutique hotel','🥦 Organic store',
  '📲 Mobile app','🤖 AI service',
];
const EN_TITLES = [
  'Coffee shop landing','Personal trainer site','Online clothing store','Barbershop with booking','Photographer portfolio',
  'Real estate agency','Online courses platform','Law firm website','Medical clinic','Food delivery service',
  'Beauty salon & SPA','SaaS product landing','Travel agency','Car dealership','Children\'s center',
  'Wedding agency','Accounting services','Veterinary clinic','Yoga & meditation studio','Craft brewery',
  'Electronics store','Fitness club','Sushi restaurant','Construction company','Flower shop',
  'Interior design studio','Private kindergarten','Brunch cafe','Pizzeria with delivery',
  'Steakhouse & grill','Bakery & pastry shop','Vegan cafe','Cleaning company','Dental clinic',
  'Taxi & transfer service','Home repair company','Massage & wellness SPA','Sports equipment store','Jewelry store',
  'Furniture & decor store','Pet supplies store','Cosmetics store','Logistics company','HR agency',
  'Security company','Event management agency','Digital marketing agency','Music school','Escape rooms',
  'Wedding photographer','Coworking space','Language school',
  'Asian noodle bar','Car wash & detailing','Online bookstore','Financial consulting','Physiotherapy rehab center',
  'Coding bootcamp','Tattoo studio','Boutique hotel','Organic grocery store',
  'Mobile app landing','AI product landing',
];
const EN_PROMPTS = [
  'Build a landing for coffee shop with menu, delivery and online orders',
  'Create a site for a personal trainer with schedule, pricing and booking',
  'Build a clothing store with catalog, filters and cart',
  'Create a barbershop site with online booking, pricing and team',
  'Build a photographer portfolio with gallery, services and lead form',
  'Create a real estate agency site with listings, search and callback form',
  'Build a landing for online courses with program, reviews and payment',
  'Create a law firm site with services, attorney team and free consultation',
  'Build a medical clinic site with services, doctors, pricing and booking',
  'Create a food delivery site with dish catalog, cart and order tracking',
  'Build a beauty salon site with services, masters, pricing and booking',
  'Create a SaaS startup landing with product features, pricing and sign-up',
  'Build a travel agency site with tours, destinations and booking form',
  'Create a car dealership site with catalog, credit calculator and test drive',
  'Build a children\'s center site with programs, schedule and enrollment',
  'Create a wedding agency site with portfolio, packages and lead form',
  'Build an accounting company site with services, pricing and consultation form',
  'Create a vet clinic site with services, doctors, pricing and pet booking',
  'Build a yoga studio site with class schedule, instructors and online booking',
  'Create a craft brewery site with tap list, brand story and events',
  'Build an electronics store with catalog, filters, cart and product comparison',
  'Create a gym site with memberships, trainers, group class schedule and offers',
  'Build a sushi restaurant site with online menu, delivery and table reservation',
  'Create a construction company site with project portfolio, services and cost calculator',
  'Build a flower shop site with bouquet catalog, delivery and bouquet builder',
  'Create an interior design studio site with project portfolio, services and inquiry form',
  'Build a private kindergarten site with programs, schedule, teachers and enrollment form',
  'Build a brunch cafe site with menu, interior photos and table reservation',
  'Create a pizzeria site with online menu, pizza builder and delivery',
  'Build a steakhouse site with menu, dish photos, table reservation and atmosphere',
  'Create a bakery site with pastry catalog, daily specials and custom cake orders',
  'Build a vegan cafe site with menu, brand story, delivery and ingredient map',
  'Create a cleaning company site with services, pricing, before-after photos and booking',
  'Build a dental clinic site with services, doctors, pricing and online appointment',
  'Create a taxi service site with route calculator, fares and online ride booking',
  'Build a home repair company site with portfolio, services, pricing and lead form',
  'Create a massage center site with treatment types, masters, pricing and online booking',
  'Build a sports equipment store with catalog, category filters and cart',
  'Create a handmade jewelry store with catalog, filters and cart',
  'Build a furniture store with room-based catalog, 3D view and order form',
  'Create a pet supplies store with catalog by animal type, delivery and promotions',
  'Build a cosmetics store with catalog, reviews and skin type finder',
  'Create a logistics company site with services, delivery cost calculator and tracking',
  'Build an HR agency site with vacancies, employer and candidate sections',
  'Create a security company site with services, objects, team and inquiry form',
  'Build an event agency site with event portfolio, services and inquiry form',
  'Create a digital marketing agency site with case studies, services and client form',
  'Build a music school site with courses, teachers, schedule and trial lesson signup',
  'Create an escape room site with room descriptions, difficulty levels and online booking',
  'Build a wedding photographer site with gallery, packages and date booking form',
  'Create a coworking space site with plans, workspace photos, amenities and booking',
  'Build a language school site with courses, levels, teachers and placement test',
  'Create an Asian noodle bar site with menu, dish photos, delivery and table reservation',
  'Build a car wash & detailing site with pricing, online booking and before-after photos',
  'Create an online bookstore with catalog by genre, recommendations and checkout',
  'Build a financial consulting site with services, case studies and consultation form',
  'Create a rehab center site with services, doctors, recovery programs and booking',
  'Build a coding school landing with courses, curriculum and free lesson signup',
  'Create a tattoo studio site with portfolio, artists, pricing and booking form',
  'Build a boutique hotel site with rooms, pricing, interior photos and online booking',
  'Create an organic grocery store with catalog, delivery and weekly box subscription',
  'Build a mobile app landing with feature overview, screenshots and download links',
  'Create an AI product landing with feature demo, pricing and sign-up form',
];

const DEMO_ITEMS_EN: DemoItem[] = DEMO_ITEMS_RU.map((item, i) => ({
  ...item,
  tag: EN_TAGS[i] ?? item.tag,
  title: EN_TITLES[i] ?? item.title,
  prompt: EN_PROMPTS[i] ?? item.prompt,
}));

export const getPORTFOLIO = (lang: Lang) => lang === 'ru' ? DEMO_ITEMS_RU : DEMO_ITEMS_EN;